/**
 * Cell 0 OS — Security Auditing
 *
 * Wraps cell0/engine/security/tool_audit.py
 * Exposes the immutable forensic logs generated by AI engine tool usage.
 */

import { PythonBridge } from "../agents/python-bridge.js";

export interface AuditEvent {
    eventId: string;
    timestamp: string;
    agentId: string;
    toolName: string;
    action: string;
    status: "success" | "denied" | "failed";
    hash: string;
}

export class SecurityAuditor {
    private bridge: PythonBridge;

    constructor(bridge: PythonBridge) {
        this.bridge = bridge;
    }

    /**
     * Retrieves the cryptographically signed forensic log array from Python.
     */
    async fetchLogs(limit: number = 100): Promise<AuditEvent[]> {
        if (!this.bridge.isReady()) return [];
        try {
            const res = await this.bridge.post<{ events: AuditEvent[] }>("/api/audit/logs", { limit });
            return res.events || [];
        } catch (error) {
            console.error("[SecurityAuditor] Failed to fetch audit logs:", error);
            return [];
        }
    }
}
